
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 23;
  public static final int PARFERMANTE = 17;
  public static final int CSTENTIERE = 24;
  public static final int LIRE = 9;
  public static final int OPERMULTET = 30;
  public static final int ECRIRE = 8;
  public static final int FONCTION = 7;
  public static final int ALORS = 19;
  public static final int TANTQUE = 13;
  public static final int VIRGULE = 6;
  public static final int REPETER = 14;
  public static final int OPELOGIQUE = 28;
  public static final int NON = 22;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 15;
  public static final int OPERTN = 27;
  public static final int SINON = 20;
  public static final int EGALE = 11;
  public static final int OPERMULTOU = 31;
  public static final int ENTIER = 10;
  public static final int EOF = 0;
  public static final int OPELOGIQUET = 29;
  public static final int RETOURNER = 12;
  public static final int PAROUVRANTE = 16;
  public static final int SI = 18;
  public static final int error = 1;
  public static final int OPER = 25;
  public static final int DEBUT = 3;
  public static final int FINSI = 21;
  public static final int FIN = 4;
  public static final int OPERT = 26;
  public static final int PROGRAMME = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME",
  "DEBUT",
  "FIN",
  "POINTVIRGULE",
  "VIRGULE",
  "FONCTION",
  "ECRIRE",
  "LIRE",
  "ENTIER",
  "EGALE",
  "RETOURNER",
  "TANTQUE",
  "REPETER",
  "FINTANTQUE",
  "PAROUVRANTE",
  "PARFERMANTE",
  "SI",
  "ALORS",
  "SINON",
  "FINSI",
  "NON",
  "IDF",
  "CSTENTIERE",
  "OPER",
  "OPERT",
  "OPERTN",
  "OPELOGIQUE",
  "OPELOGIQUET",
  "OPERMULTET",
  "OPERMULTOU"
  };
}

